OnlineCourse.Web/Entities/Common/BaseEntity.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineCourse.Web.Entities.Common
{
    public abstract class BaseEntity
    {
        [Key]
        public int Id { get; set; }
    }
}

OnlineCourse.Web/Entities/Products/Product.cs
using OnlineCourse.Web.Entities.Common;
using System.ComponentModel.DataAnnotations;


namespace OnlineCourse.Web.Entities.Products
{
    public class Product : BaseEntity
    {
        #region properties

        [MaxLength(255)]
        [Required]
        public string ProductName { get; set; }

        [Required]
        [MaxLength(255)]
        public string ShortDescription { get; set; }

        [Required]
        public string ProductDescription { get; set; }

        public int Inventory { get; set; }

        [MaxLength(1000)]
        public string Tags { get; set; }

        [Required]
        [MaxLength(300)]
        public string Image { get; set; }

        public int Price { get; set; }

        public bool IsActive { get; set; }

        #endregion

        #region MyRegion

        public ICollection<ProductGallery> ProductGalleries { get; set; }
        public ICollection<ProductSelectedCategory> ProductSelectedCategories { get; set; }

        #endregion
    }
}

OnlineCourse.Web/Entities/Products/ProductCategory.cs
using OnlineCourse.Web.Entities.Common;
using System.ComponentModel.DataAnnotations;

namespace OnlineCourse.Web.Entities.Products
{
    public class ProductCategory : BaseEntity
    {
        #region properties

        public int? ParentId { get; set; }

        [Required]
        [MaxLength(300)]
        public string Title { get; set; }

        [Required]
        [MaxLength(300)]
        public string Slug { get; set; }

        public bool IsActive { get; set; }

        #endregion

        #region relations

        public ICollection<ProductSelectedCategory> ProductSelectedCategories { get; set; }

        public ProductCategory Parent { get; set; }

        #endregion
    }
}

OnlineCourse.Web/Entities/Products/ProductGallery.cs
using OnlineCourse.Web.Entities.Common;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineCourse.Web.Entities.Products
{
    public class ProductGallery : BaseEntity
    {
        #region properties

        public int ProductId { get; set; }

        [Required]
        [MaxLength(300)]
        public string ImageName { get; set; }

        #endregion

        #region relations

        public Product Product { get; set; }

        #endregion
    }
}

OnlineCourse.Web/Entities/Products/ProductSelectedCategory.cs
using OnlineCourse.Web.Entities.Common;

namespace OnlineCourse.Web.Entities.Products
{
    public class ProductSelectedCategory : BaseEntity
    {
        #region properties

        public int ProductId { get; set; }
        public int ProductCategoryId { get; set; }

        #endregion

        #region relations

        public Product Product { get; set; }
        public ProductCategory ProductCategory { get; set; }

        #endregion
    }
}

OnlineCourse.Web/Models/ErrorViewModel.cs
namespace OnlineCourse.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineCourse.Web/Areas/Admin/Controllers/AdminBaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminBaseController : Controller
    {

    }
}

OnlineCourse.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.Areas.Admin.Controllers
{
    public class HomeController : AdminBaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OnlineCourse.Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineCourse.Web.Context;

namespace OnlineCourse.Web.Areas.Admin.Controllers
{
    public class ProductController : AdminBaseController
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext contex)
        {
            _context = contex;
        }

        public IActionResult Index()
        {
            var products = _context.Products.ToList();
            return View();
        }
    }
}

OnlineCourse.Web/Areas/Admin/ViewComponents/AdminSidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.Areas.Admin.ViewComponents
{
    public class AdminSidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("AdminSidebar");
        }
    }
}

OnlineCourse.Web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.Controllers
{
    public class ContactController : Controller
    {
        [Route("contact-us")]
        public IActionResult ContactUs()
        {
            return View();
        }
    }
}

OnlineCourse.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.Controllers
{
    public class HomeController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact-us")]
        public IActionResult ContactUs()
        {
            return View();
        }
    }
}

OnlineCourse.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineCourse.Web.Context;
using OnlineCourse.Web.Entities.Products;
using OnlineCourse.Web.Models;
using System.Diagnostics;

namespace OnlineCourse.Web.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext _context;


        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }


        // /Product/Index
        [HttpGet("products")]
        public IActionResult Index()
        {
            // create product ( C )
            //var newProduct = new Product()
            //{
            //    ProductName = "New Product",
            //    ShortDescription = "short description",
            //    ProductDescription = "long description",
            //    Image = "new_product.png",
            //    Inventory = 100,
            //    Price = 200000,
            //    Tags = "new,product,new_product",
            //    IsActive = true
            //};

            //_context.Products.Add(newProduct);
            //_context.SaveChanges();


            // get products ( R )
            var products = _context.Products.AsNoTracking().ToList(); // id : 1,2,3
            // var product = _context.Products.Single(p => p.Id == 3); // id : 3


            // update product ( U )
            //product.ProductName = "Product 3 for thrid time";
            //product.Price = 100;
            //_context.Products.Update(product);
            //_context.SaveChanges();

            // delete product ( D )
            //_context.Products.Remove(product);
            //_context.SaveChanges();

            return View(products);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineCourse.Web/ViewComponents/SiteFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.ViewComponents
{
    public class SiteFooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

OnlineCourse.Web/ViewComponents/SiteHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCourse.Web.ViewComponents
{
    public class SiteHeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            ViewBag.ComponentData = "component dynamic data";

            return View();
        }
    }
}

OnlineCourse.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "داشبورد"; 
}

OnlineCourse.Web/Areas/Admin/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "محصولات";
}

OnlineCourse.Web/Areas/Admin/Views/Shared/Components/AdminSidebar/AdminSidebar.cshtml
<div class="page-sidebar" id="sidebar">
    <!-- Page Sidebar Header-->
    <div class="sidebar-header-wrapper">
        <input type="text" class="searchinput" />
        <i class="searchicon fa fa-search"></i>
        <div class="searchhelper">به جستجوی صفحات، گزارشات، پیام ها و ایمیل خود بپردازید</div>
    </div>
    <!-- /Page Sidebar Header -->
    <!-- Sidebar Menu -->
    <ul class="nav sidebar-menu">
        <!--Dashboard-->
        <li>
            <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="menu-icon glyphicon glyphicon-home"></i>
                <span class="menu-text"> داشبورد </span>
            </a>
        </li>
        <!--UI Elements-->
        <li>
            <a href="#" class="menu-dropdown">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text"> مدیریت محصولات </span>

                <i class="menu-expand"></i>
            </a>

            <ul class="submenu">
                <li>
                    <a asp-area="Admin" asp-controller="Product" asp-action="Index">
                        <span class="menu-text">لیست محصولات</span>
                    </a>
                </li>
                <li>
                    <a href="elements.html">
                        <span class="menu-text">افزودن محصول جدید</span>
                    </a>
                </li>
            </ul>
        </li>

    </ul>
    <!-- /Sidebar Menu -->
</div>

OnlineCourse.Web/Areas/Admin/Views/Shared/_AdminFooterReferences.cshtml
 <!--Basic Scripts-->
    <script src="/admin/js/jquery.min.js"></script>
    <script src="/admin/js/bootstrap.min.js"></script>
    <script src="/admin/js/slimscroll/jquery.slimscroll.min.js"></script>

    <!--Beyond Scripts-->
    <script src="/admin/js/skins.min.js"></script>
    <script src="/admin/js/beyond.min.js"></script>


    <!--Page Related Scripts-->
    <!--Sparkline Charts Needed Scripts-->
    <script src="/admin/js/charts/sparkline/jquery.sparkline.js"></script>
    <script src="/admin/js/charts/sparkline/sparkline-init.js"></script>

    <!--Easy Pie Charts Needed Scripts-->
    <script src="/admin/js/charts/easypiechart/jquery.easypiechart.js"></script>
    <script src="/admin/js/charts/easypiechart/easypiechart-init.js"></script>

    <!--Flot Charts Needed Scripts-->
    <script src="/admin/js/charts/flot/jquery.flot.js"></script>
    <script src="/admin/js/charts/flot/jquery.flot.resize.js"></script>
    <script src="/admin/js/charts/flot/jquery.flot.pie.js"></script>
    <script src="/admin/js/charts/flot/jquery.flot.tooltip.js"></script>
    <script src="/admin/js/charts/flot/jquery.flot.orderBars.js"></script>

    <script>

        //Sets The Hidden Chart Width
        $('#dashboard-bandwidth-chart')
            .data('width', $('.box-tabbs')
                .width() - 20);
        //Visitor Sources Pie Chart
        var data = [
            {
                data: [[1, 21]],
                color: '#fb6e52'
            },
            {
                data: [[1, 12]],
                color: '#e75b8d'
            },
            {
                data: [[1, 11]],
                color: '#a0d468'
            },
            {
                data: [[1, 10]],
                color: '#ffce55'
            },
            {
                data: [[1, 46]],
                color: '#5db2ff'
            }
        ];
        var placeholder = $("#dashboard-pie-chart-sources");
        placeholder.unbind();

        $.plot(placeholder, data, {
            series: {
                pie: {
                    innerRadius: 0.45,
                    show: true,
                    stroke: {
                        width: 4
                    }
                }
            }
        });

        //Visit Chart (Main Chart)
        var data2 = [{
            color: themesecondary,
            label: "بازدید مستقیم",
            data: [[3, 2], [4, 5], [5, 4], [6, 11], [7, 12], [8, 11], [9, 8], [10, 14], [11, 12], [12, 16], [13, 9],
            [14, 10], [15, 14], [16, 15], [17, 9]],

            lines: {
                show: true,
                fill: true,
                lineWidth: .1,
                fillColor: {
                    colors: [{
                        opacity: 0
                    }, {
                        opacity: 0.4
                    }]
                }
            },
            points: {
                show: false
            },
            shadowSize: 0
        },
            {
                color: themeprimary,
                label: "لینک از سایتها",
                data: [[3, 10], [4, 13], [5, 12], [6, 16], [7, 19], [8, 19], [9, 24], [10, 19], [11, 18], [12, 21], [13, 17],
                [14, 14], [15, 12], [16, 14], [17, 15]],
                bars: {
                    order: 1,
                    show: true,
                    borderWidth: 0,
                    barWidth: 0.4,
                    lineWidth: .5,
                    fillColor: {
                        colors: [{
                            opacity: 0.4
                        }, {
                            opacity: 1
                        }]
                    }
                }
            },
            {
                color: themethirdcolor,
                label: "موتورهای جستجو",
                data: [[3, 14], [4, 11], [5, 10], [6, 9], [7, 5], [8, 8], [9, 5], [10, 6], [11, 4], [12, 7], [13, 4],
                [14, 3], [15, 4], [16, 6], [17, 4]],
                lines: {
                    show: true,
                    fill: false,
                    fillColor: {
                        colors: [{
                            opacity: 0.3
                        }, {
                            opacity: 0
                        }]
                    }
                },
                points: {
                    show: true
                }
            }
        ];
        var options = {
            legend: {
                show: false
            },
            xaxis: {
                tickDecimals: 0,
                color: '#f3f3f3'
            },
            yaxis: {
                min: 0,
                color: '#f3f3f3',
                tickFormatter: function (val, axis) {
                    return "";
                },
            },
            grid: {
                hoverable: true,
                clickable: false,
                borderWidth: 0,
                aboveData: false,
                color: '#fbfbfb'

            },
            tooltip: true,
            tooltipOpts: {
                defaultTheme: false,
                content: " <b>%x تیر ماه</b> , <b>%s</b> : <span>%y</span>",
            }
        };
        var placeholder = $("#dashboard-chart-visits");
        var plot = $.plot(placeholder, data2, options);

        //Real-Time Chart
        var realTimedata = [],
                realTimedata2 = [],
                totalPoints = 300;

        var getSeriesObj = function () {
            return [
            {
                data: getRandomData(),
                lines: {
                    show: true,
                    lineWidth: 1,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: 0
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }, {
                data: getRandomData2(),
                lines: {
                    lineWidth: 0,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: .5
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }
            ];
        };
        function getRandomData() {
            if (realTimedata.length > 0)
                realTimedata = realTimedata.slice(1);

            // Do a random walk

            while (realTimedata.length < totalPoints) {

                var prev = realTimedata.length > 0 ? realTimedata[realTimedata.length - 1] : 50,
                    y = prev + Math.random() * 10 - 5;

                if (y < 0) {
                    y = 0;
                } else if (y > 100) {
                    y = 100;
                }
                realTimedata.push(y);
            }

            // Zip the generated y values with the x values

            var res = [];
            for (var i = 0; i < realTimedata.length; ++i) {
                res.push([i, realTimedata[i]]);
            }

            return res;
        }
        function getRandomData2() {
            if (realTimedata2.length > 0)
                realTimedata2 = realTimedata2.slice(1);

            // Do a random walk

            while (realTimedata2.length < totalPoints) {

                var prev = realTimedata2.length > 0 ? realTimedata[realTimedata2.length] : 50,
                    y = prev - 25;

                if (y < 0) {
                    y = 0;
                } else if (y > 100) {
                    y = 100;
                }
                realTimedata2.push(y);
            }


            var res = [];
            for (var i = 0; i < realTimedata2.length; ++i) {
                res.push([i, realTimedata2[i]]);
            }

            return res;
        }
        // Set up the control widget
        var updateInterval = 500;
        var plot = $.plot("#dashboard-chart-realtime", getSeriesObj(), {
            yaxis: {
                color: '#f3f3f3',
                min: 0,
                max: 100,
                tickFormatter: function (val, axis) {
                    return "";
                }
            },
            xaxis: {
                color: '#f3f3f3',
                min: 0,
                max: 100,
                tickFormatter: function (val, axis) {
                    return "";
                }
            },
            grid: {
                hoverable: true,
                clickable: false,
                borderWidth: 0,
                aboveData: false
            },
            colors: ['#eee', themeprimary],
        });

        function update() {

            plot.setData(getSeriesObj());

            plot.draw();
            setTimeout(update, updateInterval);
        }
        update();


        //Initiates Easy Pie Chart instances in page
        InitiateEasyPieChart.init();

        //Initiates Sparkline Chart instances in page
        InitiateSparklineCharts.init();
    </script>

OnlineCourse.Web/Areas/Admin/Views/Shared/_AdminHeaderReferences.cshtml
<link rel="shortcut icon" href="/admin/img/favicon.png" type="image/x-icon">

<!--Basic Styles-->
<link href="/admin/css/bootstrap.min.css" rel="stylesheet" />
<link href="/admin/css/bootstrap-rtl.min.css" rel="stylesheet" />
<link href="/admin/css/font-awesome.min.css" rel="stylesheet" />
<link href="/admin/css/weather-icons.min.css" rel="stylesheet" />

<!--Fonts-->
<style>
    @@font-face {
        font-family: 'WYekan';
        src: url('/admin/fonts/BYekan.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
</style>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

<!--Beyond styles-->
<link href="/admin/css/beyond-rtl.min.css" rel="stylesheet" />
<link href="/admin/css/4095-rtl.min.css" rel="stylesheet" type="text/css" />
<link href="/admin/css/demo.min.css" rel="stylesheet" />
<link href="/admin/css/typicons.min.css" rel="stylesheet" />
<link href="/admin/css/animate.min.css" rel="stylesheet" />
<link id="skin-link" href="" rel="stylesheet" type="text/css" />

OnlineCourse.Web/Views/Contact/ContactUs.cshtml
@{
    ViewData["Title"] = "تماس با ما";
}

@section styles {
    <link rel="stylesheet" href="/site/css/custom.css"/>
}


<div id="contact-page" class="container">
    <div class="bg">
        <div class="row">
            <div class="container">
                <div class="col-sm-12" style="overflow: hidden; margin-bottom: 40px">
                    <h2 class="title text-center">تمـاس با مـا</h2>    			    						<div id="gmap" class="contact-map">
                        <img src="/site/images/home/Map.jpg" alt="Map">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="contact-form">
                    <h2 class="title text-center">با ما در ارتباط باشیـد</h2>
                    <div class="status alert alert-success" style="display: none"></div>
                    <form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
                        <div class="form-group col-md-6">
                            <input type="text" name="name" class="form-control" required="required" placeholder="نام">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="email" name="email" class="form-control" required="required" placeholder="ایمیـل">
                        </div>
                        <div class="form-group col-md-12">
                            <input type="text" name="subject" class="form-control" required="required" placeholder="موضـوع">
                        </div>
                        <div class="form-group col-md-12">
                            <textarea name="message" id="message" required="" class="form-control" rows="8" placeholder="پیغـام شمـا"></textarea>
                        </div>
                        <div class="form-group col-md-12">
                            <input type="submit" name="submit" class="btn btn-primary pull-right" value="ارسـال">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="contact-info">
                    <h2 class="title text-center">اطلاعات تماس</h2>
                    <address>
                        <p>گـروه تکنوگـرافی 1614</p>
                        <p>ایـران - آذربایجـان غربـی - خـوی</p>
                        <p>مجتـمع تجـاری تفریحـی شمس - طبـقه 2 - پلاک 54</p>
                        <p>تلفن تماس : 80 21 24 36 044</p>
                        <p>فکس : 80 21 24 36 044</p>
                        <p style="font-family: tahoma;">ایمیـل : info@1614GP.ir</p>
                    </address>
                    <div class="social-networks">
                        <h2 class="title text-center">شبکـه های اجتـماعی</h2>
                        <span class="socials-share share">
                            <ul>
                                <a href="#">
                                <li>
                                    <label>بلـه</label>
                                    <img src="/site/images/product-details/Bale.png">
                                </li>
                                </a>
                                <a href="#">
                                <li>
                                    <label>سـروش</label>
                                    <img src="/site/images/product-details/Soroush.png">
                                </li>
                                </a>
                                <a href="#">
                                <li>
                                    <label>اینستاگرام</label>
                                    <img src="/site/images/product-details/Instagram.png">
                                </li>
                                </a>
                            </ul>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

OnlineCourse.Web/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "تماس با ما";
}

OnlineCourse.Web/Views/Product/Index.cshtml
@using OnlineCourse.Web.Entities.Products
@model List<Product>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <ul>
                @foreach (var product in Model)
                {
                    <li>@product.ProductName @product.Price</li>
                }
            </ul>
        </div>
    </div>
</div>

OnlineCourse.Web/Views/Product/SecondIndex.cshtml
@{
    ViewData["Title"] = "Products second Page";
}

<div class="text-center">
    <h1 class="display-4">Products second page</h1>
</div>

OnlineCourse.Web/Views/Shared/Components/SiteFooter/Default.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-Before">
        <div class="container">
            <div class="block-news">
                <div class="row">
                    <h3>با عضویت در خبـرنامه ما از تخفیفات ویـژه ما با خبـر شوید ... </h3>
                    <div class="searchform newslatter">
                        <input type="text" placeholder="آدرس ایمیـل شما ..." />
                        <button type="submit" class="btn btn-default">
                            <i class="fa fa-arrow-circle-o-left"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="address">
                        <img src="/site/images/home/map.png" alt="" />
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="/site/images/home/map.png" alt="" />
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="companyinfo">
                        <h2><span>SHOP</span>CENTER</h2>
                        <h4>درباره ما :</h4>
                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده ازلورملورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom" style="direction: ltr !important;">
        <div class="container">
            <div class="row">
                <p class="pull-left">
                    Copyright © 2018
                    <a target="_blank" href="http://www.1614GP.ir"><b>1614Group</b></a>. All rights reserved.
                </p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

OnlineCourse.Web/Views/Shared/_FooterReferences.cshtml
<script src="/site/js/jquery.js"></script>
<script src="/site/js/bootstrap.min.js"></script>
<script src="/site/js/jquery.scrollUp.min.js"></script>
<script src="/site/js/price-range.js"></script>
<script src="/site/js/jquery.prettyPhoto.js"></script>
<script src="/site/js/main.js"></script>

OnlineCourse.Web/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <partial name="_HeaderReferences" />
    @RenderSection("styles", false)
</head>
<body>
    @await Component.InvokeAsync("SiteHeader")
    @RenderBody()
    @await Component.InvokeAsync("SiteFooter")
    <partial name="_FooterReferences" />
    @RenderSection("scripts", false)
</body>
</html>